using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using BulkValidation.Core.Enums;
using BulkValidation.SourceGeneration.Models;
using BulkValidation.SourceGeneration.Static;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BulkValidation.SourceGeneration;

public class SourceGeneratorValidateAttr : IIncrementalGenerator
{
    private readonly ImmutableArray<(string @namespace, string shortcut, ArgumentMetadata[] additionalArgs)> _baseRules =
        ImmutableArray.CreateRange([("BulkValidation.Core.Rules.ExistenceRule", "Exists", new []
        {
            new ArgumentMetadata("BulkValidation.Core.Enums.Quantifier", "quantifier", "BulkValidation.Core.Enums.Quantifier.All")
        }), ("BulkValidation.Core.Rules.NotExistenceRule", "NotExists", new []
        {
            new ArgumentMetadata("BulkValidation.Core.Enums.Quantifier", "quantifier", "BulkValidation.Core.Enums.Quantifier.All")
        })]);
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var optionsProvider = context.AnalyzerConfigOptionsProvider
            .Select((provider, _) =>
            {
                provider.GlobalOptions.TryGetValue(
                    "build_property.RootNamespace".ToLowerInvariant(),
                    out var rootNamespace);

                return string.IsNullOrWhiteSpace(rootNamespace)
                    ? "Generated"
                    : rootNamespace;
            });

        var propWithValidateAttr = GetPropertiesWithValidateAttribute(context)
            .Combine(optionsProvider);

        context.RegisterSourceOutput(propWithValidateAttr, GenForValidate);
    }

    private void GenForValidate(
        SourceProductionContext context,
        (ImmutableArray<IPropertySymbol?> left, string right) tuple)
    {
        var (properties, rootNamespace) = tuple;

        if (properties.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        var functionNames = new HashSet<string>();

        sb.AppendLine($$"""
                        // <auto-generated />
                        using System;
                        using System.Collections.Generic;
                        using System.Linq.Expressions;
                        using BulkValidation.Core.Models;
                        using BulkValidation.Core.Interfaces;

                        namespace {{rootNamespace}}
                        {
                            public static partial class ValidationPlanShortCutsForValidate
                            {
                        """);

        foreach (var propertySymbol in properties)
        {
            if (propertySymbol == null)
                continue;

            var entitySymbol = propertySymbol.ContainingType;

            if (entitySymbol == null)
                continue;

            var flattened = FlattenProperties(propertySymbol);

            foreach (var nested in flattened)
            {
                GenerateFunctions(
                    sb,
                    functionNames,
                    entitySymbol,
                    nested.Property,
                    nested.Path);
            }
        }

        sb.AppendLine("""
                      }
                      }
                      """);

        context.AddSource("ValidationPlanExtension.g.cs", sb.ToString());

        context.AddSource(
            "ValidationFunctions.g.cs",
            $$"""
              namespace {{rootNamespace}}
              {
                  public sealed partial class ValidationFunctions
                  {
                      {{string.Join(";\n", functionNames.Select(x =>
                          $"public const string {x} = \"{x}\""))}};
                  }
              }
              """);
    }

    private void GenerateFunctions(
        StringBuilder sb,
        HashSet<string> functionNames,
        INamedTypeSymbol entitySymbol,
        IPropertySymbol propertySymbol,
        string path)
    {
        var shortClassName = entitySymbol.Name;
        var shortPropertyName = path.Replace(".", "");

        var longClassName = entitySymbol.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat);

        var keyTypeStr = propertySymbol.Type.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat);

        foreach (var rule in _baseRules)
        {
            var kv = RuleKeyValue.GenerateKeyValue(
                entitySymbol,
                propertySymbol,
                path,
                "keyValue");

            var kvs = RuleKeyValue.GenerateKeyValues(
                entitySymbol,
                propertySymbol,
                path,
                "keyValues");

            var additionalArgs = string.Join(", ",
                rule.additionalArgs.Select(x =>
                {
                    var def = x.DefaultValue == null
                        ? ""
                        : $" = {x.DefaultValue}";

                    return $"{x.Type} {x.Name}{def}";
                }));

            if (!string.IsNullOrWhiteSpace(additionalArgs))
                additionalArgs = ", " + additionalArgs;

            var functionName =
                $"Validate{shortClassName}{rule.shortcut}{shortPropertyName}";

            sb.AppendLine($$"""
                            public static IValidationPlan {{functionName}}(
                                this IValidationPlan plan,
                                {{keyTypeStr}} value{{additionalArgs}})
                            {
                                {{kv}}
                                keyValue.WithValue(value);

                                plan.Add(
                                    new global::{{rule.@namespace}}<{{longClassName}}>(keyValue),
                                    "{{functionName}}");

                                return plan;
                            }
                            """);

            sb.AppendLine($$"""
                            public static IValidationPlan {{functionName}}(
                                this IValidationPlan plan{{additionalArgs}},
                                params {{keyTypeStr}}[] values)
                            {
                                {{kvs}}
                                keyValues.WithValue(values);

                                plan.Add(
                                    new global::{{rule.@namespace}}<{{longClassName}}>(keyValues),
                                    "{{functionName}}");

                                return plan;
                            }
                            """);

            sb.AppendLine($$"""
                            public static IValidationPlan {{functionName}}(
                                this IValidationPlan plan,
                                IEnumerable<{{keyTypeStr}}> values{{additionalArgs}})
                            {
                                {{kvs}}
                                keyValues.WithValue(values);

                                plan.Add(
                                    new global::{{rule.@namespace}}<{{longClassName}}>(keyValues),
                                    "{{functionName}}");

                                return plan;
                            }
                            """);

            functionNames.Add(functionName);
        }
    }

    private IEnumerable<(IPropertySymbol Property, string Path)> FlattenProperties(
        IPropertySymbol property,
        string? prefix = null,
        HashSet<ITypeSymbol>? visited = null)
    {
        visited ??= new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);

        var data = GetValidateData(property);

        if (data == null)
            yield break;

        var (_, mapping, fieldName) = data.Value;

        var currentName = fieldName ?? property.Name;

        var path = prefix == null
            ? currentName
            : $"{prefix}.{currentName}";

        yield return (property, path);

        // ❗ IMPORTANT: only Owned allows flattening
        if (mapping != MappingMode.Owned)
            yield break;

        if (property.Type is not INamedTypeSymbol type)
            yield break;

        if (!visited.Add(type))
            yield break;

        foreach (var nested in type.GetMembers().OfType<IPropertySymbol>())
        {
            if (GetValidateData(nested) == null)
                continue;

            foreach (var nestedProperty in FlattenProperties(
                         nested,
                         path,
                         visited))
            {
                yield return nestedProperty;
            }
        }
    }

    private (AttributeData attr, MappingMode mapping, string? fieldName)? GetValidateData(IPropertySymbol property)
    {
        var attr = property.GetAttributes()
            .FirstOrDefault(x =>
                x.AttributeClass?.ToDisplayString() ==
                "BulkValidation.Core.Attributes.ValidateAttribute");

        if (attr == null)
            return null;

        var fieldName = attr.ConstructorArguments.Length > 0
            ? attr.ConstructorArguments[0].Value?.ToString()
            : null;

        var mapping = MappingMode.Default;

        var named = attr.NamedArguments
            .FirstOrDefault(x => x.Key == "Mapping");

        if (named.Value.Value is int intValue)
            mapping = (MappingMode)intValue;

        return (attr, mapping, fieldName);
    }

    private IncrementalValueProvider<ImmutableArray<IPropertySymbol?>>
        GetPropertiesWithValidateAttribute(
            IncrementalGeneratorInitializationContext context)
    {
        return context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "BulkValidation.Core.Attributes.ValidateAttribute",
                static (node, _) => node is PropertyDeclarationSyntax,
                static (ctx, _) => ctx.TargetSymbol as IPropertySymbol)
            .Where(x => x != null)
            .Collect();
    }
}